---
- hosts: confluence
  become: True
  pre_tasks:
    - yum: name=libselinux-python state=present

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - role: ansible-confluence
