---
- hosts: confluence
  become: true

  pre_tasks:
    - name: install packages for molecule testing
      yum: name={{ item }} state=present
      with_items:
        - libselinux-python
        - net-tools

    - name: disable selinux during testing
      selinux: policy=targeted state=permissive

  roles:
    - role: williamyeh.oracle-java
    - role: ansible-role-confluence

  vars:
    java_version: 8
    java_subversion: 101
    # NOTE: speedy testing, download jdk RPM to files/ and change this to false
    java_download_from_oracle: true

    # NOTE: speedy testing, download confluence tar.gz to files/ and change
    # this to false
    confluence_download_from_remote: true
    confluence_jvm_min_mem: "1536m"
    confluence_jvm_max_mem: "1536m"
    confluence_extra_catalina_options: "-Dtest.success=true"
    confluence_proxy_name: localhost
    confluence_proxy_port: 8090
    confluence_proxy_scheme: http
