---
- hosts: confluence
  become: True
  pre_tasks:
    - yum: name=libselinux-python state=present

  roles:
    - role: galaxyprojectdotorg.postgresql
    - role: williamyeh.oracle-java
    - role: ansible-confluence

  vars:
    java_version: 8
    java_subversion: 92
