- src: https://github.com/William-Yeh/ansible-oracle-java
  version: 2.9.0
  name: williamyeh.oracle-java

- src: https://github.com/galaxyproject/ansible-postgresql
  version: master
  name: galaxyprojectdotorg.postgresql

- src: https://github.com/geerlingguy/ansible-role-haproxy
  version: 1.0.2
  name: geerlingguy.haproxy
