---
- name: config > confluence-init.properties
  template:
    src:   confluence-init.properties.j2
    dest:  "{{ confluence_install_dir }}/{{ confluence_version }}/confluence/WEB-INF/classes/confluence-init.properties"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode:  0444

- name: config > server.xml
  template:
    src:   server.xml.j2
    dest:  "{{ confluence_install_dir }}/{{ confluence_version }}/conf/server.xml"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode:  0444

- name: config > setenv.sh
  template:
    src:   setenv.sh.j2
    dest:  "{{ confluence_install_dir }}/{{ confluence_version }}/bin/setenv.sh"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    mode:  0444

- name: config > systemd directory
  file: path=/etc/systemd/system state=directory

- name: config > systemd manifest
  template:
    src:   confluence.service.j2
    dest:  "/etc/systemd/system/confluence.service"
    owner: root
    group: root
    mode:  0444
