---
- name: install > download confluence
  get_url:
    url: "{{ confluence_download_base }}/atlassian-confluence-{{ confluence_version }}.tar.gz"
    dest: /var/tmp/atlassian-confluence-{{ confluence_version }}.tar.gz

- name: install > create confluence directory
  file:
    path: "{{ confluence_install_dir }}/{{ confluence_version }}"
    state: directory
    mode: 0755

# NOTE: This uses tar directly so that we can strip the leading path
- name: extract confluence archive
  command: tar --strip-components=1 -zxvf /var/tmp/atlassian-confluence-{{ confluence_version }}.tar.gz
  args:
    chdir: "{{ confluence_install_dir }}/{{ confluence_version }}"
    creates: "{{ confluence_install_dir }}/{{ confluence_version }}/LICENSE"

- name: install > set directory permissions
  file:
    path: "{{ confluence_install_dir }}/{{ confluence_version }}"
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
    recurse: True

- name: install > create confluence home directory
  file:
    path: "{{ confluence_home }}"
    state: directory
    owner: "{{ confluence_user }}"
    group: "{{ confluence_group }}"
