---
- name: config > systemd directory
  file: path=/etc/systemd/system state=directory

- name: config > systemd manifest
  template:
    src:   confluence.service.j2
    dest:  "/etc/systemd/system/confluence.service"
    owner: root
    group: root
    mode:  0444
  notify: reload systemd units

- name: service > ensure confluence service is started
  service: name=confluence state=started enabled=yes
  when: confluence_manage_service
